# Gitea
- path: gitea/admin
  data:
    - key: password
      length: 32
      special: true

# Dex
- path: dex/grafana
  data:
    - key: client_secret
      length: 32
      special: false

- path: dex/argocd
  data:
    - key: client_secret
      length: 32
      special: false

# Tekton
- path: tekton/webhook
  data:
    - key: token
      length: 32
      special: false
